Check config.plist exists

diff --git a/tools/bootargs.j2 b/tools/bootargs.j2
--- a/tools/bootargs.j2
+++ b/tools/bootargs.j2
@@ -44,8 +44,14 @@ set_variable() {
 }
 
 # Main logic
-echo "OC4VM boot-args utility"
-echo "-----------------------"
+echo "OC4VM boot-args"
+echo "---------------"
+
+if [ ! -f $PLIST_FILE ]; then
+    echo "ERROR: $PLIST_FILE not found!"
+    exit 1
+fi
+
 case "$1" in
     -h)
         print_usage
@@ -57,6 +63,6 @@ case "$1" in
         get_variable
         ;;
     *)
-        get_variable
+        print_usage
         ;;
 esac
diff --git a/tools/vmhide.j2 b/tools/vmhide.j2
--- a/tools/vmhide.j2
+++ b/tools/vmhide.j2
@@ -37,8 +37,14 @@ set_state() {
 }
 
 # Main logic
-echo "OC4VM vmhide utility"
-echo "--------------------"
+echo "OC4VM vmhide"
+echo "------------"
+
+if [ ! -f $PLIST_FILE ]; then
+    echo "ERROR: $PLIST_FILE not found!"
+    exit 1
+fi
+
 case "$1" in
     -h)
         print_usage
