qemu/qemu New shell script to run macOS with optional parameters

diff --git a/qemu/qemu-macos.j2 b/qemu/qemu-macos.j2
--- a/qemu/qemu-macos.j2
+++ b/qemu/qemu-macos.j2
@@ -3,15 +3,122 @@
 # {{VERSION}}
 # {{VARIANT}}
 
-#set -x
+if [[ -v OC4VM_QEMU_DEBUG ]]; then
+	set -x
+fi
+
+echo "OC4VM QEMU Runner"
+
+OPTSTRING=":a:m:o:sr:"
+ACCEL_FLAG=0
+ACCEL_TYPE="hvf"
+if [[ $(arch) == 'arm64' ]]; then
+  ACCEL_TYPE="tcg"
+fi
+MEMORY_FLAG=0
+MEMORY_SIZE="4"
+OPENCORE_FLAG=0
+OPENCORE_IMG="opencore.qcow2"
+SERIAL_FLAG=0
+RECOVERY_FLAG=0
+RECOVERYOS_IMG=""
+
+usage () {
+	cat <<HELP
+ NAME:
+	$0
+
+ SYNOPSIS:
+	$0 [-a {hvf | kvm | tcg}] [-m <memory-size>] [-o <opencore-image>] [-r <recovery-image>] [-s]
+
+ DESCRIPTION:
+	Run macOS using QEMU
+
+ OPTIONS:
+	-a ACCEL              QEMU accelerator to use.
+	-m MEMORY             specifies amountof memory to allocate to VM.
+	-o OPENCORE-IMAGE     specifies OpenCore boot image.
+	-r RECOVERY-IMAGE     specifies macOS recoveryOS image.
+	-s                    enable serial output.
+HELP
+}
+
+while getopts ${OPTSTRING} opt; do
+	case ${opt} in
+		a)
+			echo "Accelerator: ${OPTARG}"
+			ACCEL_FLAG=1
+			ACCEL_TYPE=${OPTARG}
+			# TODO: Parse and check HVF, TCG or KVM
+			case ${ACCEL_TYPE} in
+				hvf)
+					;;
+				tcg)
+					;;
+				kvm)
+					;;
+				*)
+					echo "ERROR: Invalid accelerator option: ${OPTARG}"
+					usage
+				 	exit 1
+					;;
+			esac
+			;;
+		m)
+			echo "Memory size: ${OPTARG}"
+			MEMORY_FLAG=1
+			MEMORY_SIZE=${OPTARG}
+			if [ ! -z "${MEMORY_SIZE//[0-9]}" ]; then
+        		echo "ERROR: Memory size $MEMORY_SIZE not an integer!"
+			  	exit 1
+			fi
+			if [ "$MEMORY_SIZE" -lt "4" ]; then
+    			echo "ERROR: Memory size must be 4GB or greater!"
+			  	exit 1
+			fi
+			;;
+		o)
+			echo "OpenCore image: ${OPTARG}"
+			OPENCORE_FLAG=1
+			OPENCORE_IMG=${OPTARG}
+			if [ ! -f $OPENCORE_IMG ]; then
+        		echo "ERROR: $OPENCORE_IMG not found!"
+			  	exit 1
+			fi
+			;;
+		r)
+			echo "Recovery image: ${OPTARG}"
+			RECOVERY_FLAG=1
+			RECOVERYOS_IMG=${OPTARG}
+			if [ ! -f $RECOVERYOS_IMG ]; then
+				echo "ERROR: $RECOVERYOS_IMG not found!"
+				exit 1
+			fi
+			;;
+		s)
+			echo "Serial output enabled"
+			SERIAL_FLAG=1
+			;;
+		:)
+			echo "ERROR: Option -${OPTARG} requires an argument."
+			usage
+			exit 1
+			;;
+		?)
+			echo "ERROR: Invalid option: -${OPTARG}"
+			usage
+			exit 1
+			;;
+	esac
+done
 
 args=(
--name "{{DESCRIPTION}}"
--cpu host,pdpe1gb=off,vmware-cpuid-freq=on,vendor=GenuineIntel
+-name "macOS Intel"
+-cpu Skylake-Client-noTSX-IBRS,vmware-cpuid-freq=on,vendor=GenuineIntel,check
 -smp cpus=2,sockets=1,cores=2,threads=1
 -machine q35,vmport=off,i8042=off,hpet=off
--accel hvf
--m 4096
+-accel $ACCEL_TYPE
+-m "$MEMORY_SIZE"G
 -nodefaults
 -device virtio-net-pci,mac=66:C9:75:99:89:AC,netdev=net0
 -netdev user,id=net0,hostfwd=tcp::5959-:5900,hostfwd=tcp::2222-:22
@@ -21,22 +128,31 @@ args=(
 -drive if=pflash,format=raw,unit=0,file.filename=./edk2-x86_64-code.fd,file.locking=off,readonly=on
 -drive if=pflash,format=raw,unit=1,file=./efi_vars.fd
 -device virtio-blk,drive=opencore,bootindex=0
--drive if=none,media=disk,id=opencore,file=opencore.qcow2,discard=unmap,detect-zeroes=unmap,format=qcow2
+-drive if=none,media=disk,id=opencore,file="$OPENCORE_IMG",discard=unmap,detect-zeroes=unmap
 -device virtio-blk,drive=macos,bootindex=1
 -drive if=none,media=disk,id=macos,file=macos.qcow2,discard=unmap,detect-zeroes=unmap,format=qcow2
-{%- if RECOVERY == '1' %}
--device virtio-blk,drive=macos,bootindex=2
--drive if=none,media=disk,id=macos,file=basesystem.qcow2,discard=unmap,detect-zeroes=unmap,format=qcow2
-{%- endif -%}
 -device qemu-xhci
 -device usb-tablet
 -device usb-kbd
--smbios type=2
-{%- if SERIAL == 'TRUE' %}
--chardev stdio,id=char0,mux=on,logfile=serial-amd.log,signal=off
+-smbios type=1
+-audiodev coreaudio,id=audio0
+-device ich9-intel-hda
+-device hda-output,audiodev=audio0
+)
+
+if [ $SERIAL_FLAG = 1 ]; then
+args+=(
+-chardev stdio,id=char0,mux=on,logfile=serial.log,signal=off
 -serial chardev:char0
 -mon chardev=char0
-{%- endif %}
 )
+fi
+
+if [ $RECOVERY_FLAG = 1 ]; then
+args+=(
+-device virtio-blk,drive=recoveryos,bootindex=2
+-drive if=none,media=disk,id=recoveryos,file=$RECOVERYOS_IMG,discard=unmap,detect-zeroes=unmap
+)
+fi
 
 qemu-system-x86_64 "${args[@]}"
